In [1]:
import pandas as pd
df = pd.read_csv("2018_WoS.csv", sep=";", header=None)

### Data: 
The data is in the file 2018_WoS.csv.The separator for the columns is “;” (rather than “,”).There is no header.

### Columns: 
Publication code. A unique code that identifies the publication.1: Journal name.2: Title.3: Abstract.

In [2]:
df.head()

,0,1,2,3
0,405496000001,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Research on the reliability of friction system...,"In this paper, the reliability of a non-linear..."
1,405496000002,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Vector solitons in coupled nonlinear Schroding...,The dynamics of two-component solitons is stud...
2,405496000003,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Analysis of cyclical behavior in time series o...,In this paper we have analyzed scaling propert...
3,405496000004,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Impact of marine reserve on maximum sustainabl...,Multispecies fisheries management requires man...
4,405496000005,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Double-well chimeras in 2D lattice of chaotic ...,We investigate spatio-temporal dynamics of a 2...

In [3]:
df.tail()

,0,1,2,3
1630345,501568200001,TURKISH JOURNAL OF BIOCHEMISTRY-TURK BIYOKIMYA...,"TBS International Biochemistry Congress 2018, ...",NaN
1630346,502087800001,JOURNAL OF GASTROINTESTINAL AND LIVER DISEASES,The 5th Romanian-German Symposium of Gastroent...,NaN
1630347,502088600001,JOURNAL OF GASTROINTESTINAL AND LIVER DISEASES,The XXXVIIIth National Congress of Gastroenter...,NaN
1630348,502089100001,JOURNAL OF GASTROINTESTINAL AND LIVER DISEASES,The 10th National Symposium on Inflammatory Bo...,NaN
1630349,502648200001,JOURNAL OF PORPHYRINS AND PHTHALOCYANINES,Electrochemistry of zinc tetraarylporphyrins c...,Two series of zinc tetraarylporphyrins contain...

In [4]:
df.shape

(1630350, 4)

In [5]:
df.columns = ['Publication_Code','Journal_Name', 'Title', 'Abstract']
df.head()

,Publication_Code,Journal_Name,Title,Abstract
0,405496000001,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Research on the reliability of friction system...,"In this paper, the reliability of a non-linear..."
1,405496000002,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Vector solitons in coupled nonlinear Schroding...,The dynamics of two-component solitons is stud...
2,405496000003,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Analysis of cyclical behavior in time series o...,In this paper we have analyzed scaling propert...
3,405496000004,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Impact of marine reserve on maximum sustainabl...,Multispecies fisheries management requires man...
4,405496000005,COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERI...,Double-well chimeras in 2D lattice of chaotic ...,We investigate spatio-temporal dynamics of a 2...

#### NOTES:
- perhaps use authors of similar publication

In [6]:
for i in range(1000):
    print(df.iloc[i, 1])

COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
BERNOULLI
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
SCIENCE CHINA-INFORMATION SCIENCES
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
FOOD HYDROCOLLOIDS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
JOURNAL OF CELLULAR AUTOMATA
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
NURSING HISTORY REVIEW
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
FOOD CHEMISTRY
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
MEASUREMENT
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
RECORDS OF NATURAL PRODUCTS
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE

JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
JOURNAL OF APPLIED POLYMER SCIENCE
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
JOURNAL OF CELLULAR PHYSIOLOGY
BIOINTERPHASES
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
SCIENCE OF THE TOTAL ENVIRONMENT
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
COMPUTER SPEECH AND LANGUAGE
JOURNAL OF COMBINATORIAL THEORY SERIES A
JOURNAL OF COMBINATORIAL THEORY SERIES A
JOURNAL OF COMBINATORIAL THEORY SERIES A
JOURNAL OF COMBINATORIAL THEORY SERIES A
JOURNAL OF COMBINATORIAL THEORY SERIES A
JOURNAL OF COMBINATORIAL THEORY SERIES A
JOURNAL OF COMBINATORIAL THEORY SERIES A
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
MATHEMATICAL BIOSCIENCES AND ENGINEERING
IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA
LEUKEMIA & LYMPHOMA

In [7]:
import numpy as np

chosen_idx = np.random.choice(1000, replace=False, size=50)
sample_df = df.iloc[chosen_idx]

In [8]:
sample_df.shape

(50, 4)

In [11]:
journal_names = df.Journal_Name.unique()

In [13]:
journal_names.shape

(12912,)

In [15]:
j_list = journal_names.tolist()

In [16]:
j_list

['COMMUNICATIONS IN NONLINEAR SCIENCE AND NUMERICAL SIMULATION',
 'IEEE JOURNAL OF SELECTED TOPICS IN QUANTUM ELECTRONICS',
 'JOURNAL OF CIRCUITS SYSTEMS AND COMPUTERS',
 'BERNOULLI',
 'FOOD CHEMISTRY',
 'SCIENCE CHINA-INFORMATION SCIENCES',
 'FOOD HYDROCOLLOIDS',
 'JOURNAL OF CELLULAR AUTOMATA',
 'NURSING HISTORY REVIEW',
 'JOURNAL OF APPLIED POLYMER SCIENCE',
 'MEASUREMENT',
 'RECORDS OF NATURAL PRODUCTS',
 'JOURNAL OF CELLULAR PHYSIOLOGY',
 'BIOINTERPHASES',
 'SCIENCE OF THE TOTAL ENVIRONMENT',
 'INTERNATIONAL JOURNAL OF COMPUTATIONAL METHODS',
 'COMPUTER SPEECH AND LANGUAGE',
 'JOURNAL OF COMBINATORIAL THEORY SERIES A',
 'MATHEMATICAL BIOSCIENCES AND ENGINEERING',
 'LEUKEMIA & LYMPHOMA',
 'JOURNAL OF MATHEMATICAL ANALYSIS AND APPLICATIONS',
 'INTERNATIONAL JOURNAL OF AUTOMOTIVE TECHNOLOGY',
 'INFORMATION FUSION',
 '2D MATERIALS',
 'JOURNAL OF FOOD ENGINEERING',
 'JOURNAL OF HAZARDOUS MATERIALS',
 'POSTHARVEST BIOLOGY AND TECHNOLOGY',
 'DISCRETE AND CONTINUOUS DYNAMICAL SYSTEMS',
 'IEEE TRANSACTIONS ON POWER ELECTRONICS',
 'INTERNATIONAL JOURNAL OF REMOTE SENSING',
 'INTERNATIONAL JOURNAL OF PATTERN RECOGNITION AND ARTIFICIAL INTELLIGENCE',
 'IEEE TRANSACTIONS ON ELECTROMAGNETIC COMPATIBILITY',
 'BIOMEDICAL SIGNAL PROCESSING AND CONTROL',
 'SPECTROCHIMICA ACTA PART A-MOLECULAR AND BIOMOLECULAR SPECTROSCOPY',
 'INTERNATIONAL JOURNAL OF ELECTRICAL POWER & ENERGY SYSTEMS',
 'TALANTA',
 'SIGNAL PROCESSING',
 'OPTICS AND LASER TECHNOLOGY',
 'PHYSICA A-STATISTICAL MECHANICS AND ITS APPLICATIONS',
 'EUROPEAN JOURNAL OF OPERATIONAL RESEARCH',
 'ICARUS',
 'JOURNAL OF COMPUTATIONAL AND APPLIED MATHEMATICS',
 'NONLINEAR ANALYSIS-REAL WORLD APPLICATIONS',
 'JOURNAL OF NUMBER THEORY',
 'JOURNAL OF STATISTICAL PLANNING AND INFERENCE',
 'NEW ASTRONOMY',
 'PROTEIN EXPRESSION AND PURIFICATION',
 'PHYSICA E-LOW-DIMENSIONAL SYSTEMS & NANOSTRUCTURES',
 'JOURNAL OF MATERIALS SCIENCE',
 'APPLIED CATALYSIS B-ENVIRONMENTAL',
 'ROBOTICS AND COMPUTER-INTEGRATED MANUFACTURING',
 'MICROCHEMICAL JOURNAL',
 'FOOD QUALITY AND PREFERENCE',
 'PATTERN RECOGNITION',
 'ULTRASONICS SONOCHEMISTRY',
 'ADDICTIVE BEHAVIORS',
 'APPLIED MATHEMATICS LETTERS',
 'JOURNAL OF PURE AND APPLIED ALGEBRA',
 'APPLIED AND COMPUTATIONAL HARMONIC ANALYSIS',
 'MECHANICAL SYSTEMS AND SIGNAL PROCESSING',
 'APPLIED ACOUSTICS',
 'FUTURE GENERATION COMPUTER SYSTEMS-THE INTERNATIONAL JOURNAL OF ESCIENCE',
 'PLASMA PHYSICS AND CONTROLLED FUSION',
 'MATERIALS LETTERS',
 'ADVANCES IN APPLIED MATHEMATICS',
 'JOURNAL OF COMPUTER AND SYSTEM SCIENCES',
 'JOURNAL OF MAGNETISM AND MAGNETIC MATERIALS',
 'IEEE TRANSACTIONS ON IMAGE PROCESSING',
 'JOURNAL OF MEMBRANE SCIENCE',
 'SCRIPTA MATERIALIA',
 'APPLIED ERGONOMICS',
 'JOURNAL OF SYMBOLIC COMPUTATION',
 'BIOSENSORS & BIOELECTRONICS',
 'SENSORS AND ACTUATORS B-CHEMICAL',
 'COMPOSITIO MATHEMATICA',
 'INTERNATIONAL JOURNAL OF OCCUPATIONAL MEDICINE AND ENVIRONMENTAL HEALTH',
 'ELECTRICAL ENGINEERING IN JAPAN',
 'MATHEMATICS AND COMPUTERS IN SIMULATION',
 'JOURNAL OF MATERIALS PROCESSING TECHNOLOGY',
 'SEPARATION AND PURIFICATION TECHNOLOGY',
 'BEHAVIOURAL BRAIN RESEARCH',
 'EUROPEAN JOURNAL OF COMBINATORICS',
 'INTERNATIONAL JOURNAL OF HUMAN-COMPUTER STUDIES',
 'JOURNAL OF COLLOID AND INTERFACE SCIENCE',
 'JOURNAL OF SUPERCRITICAL FLUIDS',
 'COMPOSITES PART B-ENGINEERING',
 'JOURNAL OF AFFECTIVE DISORDERS',
 'FOOD MICROBIOLOGY',
 'AQUACULTURE',
 'COMMUNICATIONS IN CONTEMPORARY MATHEMATICS',
 'APPLIED MATHEMATICS AND COMPUTATION',
 'FUEL',
 'JOURNAL OF ALGEBRAIC GEOMETRY',
 'GEODERMA',
 'RENEWABLE ENERGY',
 'INTERNATIONAL TRANSACTIONS IN OPERATIONAL RESEARCH',
 'SCIENTIA AGRICOLA',
 'MATHEMATICS OF COMPUTATION',
 'ANALYSIS AND APPLICATIONS',
 'COMPOSITE INTERFACES',
 'MECHANISM AND MACHINE THEORY',
 'SCANDINAVIAN JOURNAL OF OCCUPATIONAL THERAPY',
 'INTERNATIONAL JOURNAL OF THERMAL SCIENCES',
 'APPLIED NUMERICAL MATHEMATICS',
 'MATHEMATICAL INEQUALITIES & APPLICATIONS',
 'NEUROCOMPUTING',
 'SHIPS AND OFFSHORE STRUCTURES',
 'COMPUTERS & STRUCTURES',
 'ANNALS OF NUCLEAR ENERGY',
 'FISHERIES RESEARCH',
 'INTERNATIONAL JOURNAL OF APPLIED EARTH OBSERVATION AND GEOINFORMATION',
 'TRIBOLOGY INTERNATIONAL',
 'DEVELOPMENTAL AND COMPARATIVE IMMUNOLOGY',
 'TOURISM MANAGEMENT',
 'INFORMATION SCIENCES',
 'JOURNAL OF DIFFERENTIAL EQUATIONS',
 'JOURNAL OF MOLECULAR STRUCTURE',
 'CATALYSIS COMMUNICATIONS',
 'INFORMATION PROCESSING LETTERS',
 'ENGINEERING APPLICATIONS OF COMPUTATIONAL FLUID MECHANICS',
 'WEST EUROPEAN POLITICS',
 'PROGRESS IN NEURO-PSYCHOPHARMACOLOGY & BIOLOGICAL PSYCHIATRY',
 'COMPUTATIONAL MATERIALS SCIENCE',
 'NANO-MICRO LETTERS',
 'DYES AND PIGMENTS',
 'EXPERT SYSTEMS WITH APPLICATIONS',
 'SCIENTIA HORTICULTURAE',
 'OPTICS AND LASERS IN ENGINEERING',
 'PERSONALITY AND INDIVIDUAL DIFFERENCES',
 'COMPUTATIONAL STATISTICS & DATA ANALYSIS',
 'DISCRETE MATHEMATICS',
 'JOURNAL OF MEMORY AND LANGUAGE',
 'JOURNAL OF SOLID STATE CHEMISTRY',
 'JOURNAL OF THE EUROPEAN CERAMIC SOCIETY',
 'THERANOSTICS',
 'JOURNAL OF THE BRAZILIAN CHEMICAL SOCIETY',
 'TRANSACTIONS OF THE AMERICAN MATHEMATICAL SOCIETY',
 'CHEMICAL ENGINEERING JOURNAL',
 'JOURNAL OF ALLOYS AND COMPOUNDS',
 'JOURNAL OF THE AMERICAN MATHEMATICAL SOCIETY',
 'JAPANESE JOURNAL OF APPLIED PHYSICS',
 'PHYSICOCHEMICAL PROBLEMS OF MINERAL PROCESSING',
 'INTERNATIONAL DAIRY JOURNAL',
 'INFORMATION COMMUNICATION & SOCIETY',
 'JOURNAL OF ADHESION SCIENCE AND TECHNOLOGY',
 'NUCLEAR FUSION',
 'FRONTIERS OF PHYSICS',
 'JOURNAL OF THE AMERICAN CERAMIC SOCIETY',
 'COMBUSTION AND FLAME',
 'JOURNAL OF POPULATION ECONOMICS',
 'CELL JOURNAL',
 'AQUATIC MICROBIAL ECOLOGY',
 'Advances in Biochemical Engineering-Biotechnology',
 'COMPOSITE STRUCTURES',
 'STOCHASTICS AND DYNAMICS',
 'INTERNATIONAL JOURNAL OF CANCER',
 'NANOPHOTONICS',
 'MATERIALS & DESIGN',
 'JOURNAL OF AFRICAN CULTURAL STUDIES',
 'LINEAR ALGEBRA AND ITS APPLICATIONS',
 'GENE',
 'SOIL & TILLAGE RESEARCH',
 'OPTICAL SWITCHING AND NETWORKING',
 'MICROPOROUS AND MESOPOROUS MATERIALS',
 'JOURNAL OF MARINE SYSTEMS',
 'THERIOGENOLOGY',
 'INTERMETALLICS',
 'JOURNAL OF PHOTOCHEMISTRY AND PHOTOBIOLOGY A-CHEMISTRY',
 'COMPUTERS & CHEMICAL ENGINEERING',
 'ENVIRONMENT INTERNATIONAL',
 'INFORMATION AND SOFTWARE TECHNOLOGY',
 'JOURNAL OF CLEANER PRODUCTION',
 'AGRICULTURE ECOSYSTEMS & ENVIRONMENT',
 'CATENA',
 'JOURNAL OF QUANTITATIVE SPECTROSCOPY & RADIATIVE TRANSFER',
 'ENVIRONMENTAL POLLUTION',
 'JOURNAL OF BUSINESS RESEARCH',
 'CHEMOSPHERE',
 'LANDSCAPE AND URBAN PLANNING',
 'FOOD CONTROL',
 'OMEGA-INTERNATIONAL JOURNAL OF MANAGEMENT SCIENCE',
 'COMPUTERS & OPERATIONS RESEARCH',
 'APPLIED THERMAL ENGINEERING',
 'MATERIALS SCIENCE & ENGINEERING C-MATERIALS FOR BIOLOGICAL APPLICATIONS',
 'JOURNAL OF EXPERIMENTAL CHILD PSYCHOLOGY',
 'DESALINATION',
 'COMPUTATIONAL GEOMETRY-THEORY AND APPLICATIONS',
 'PHYSIOLOGICAL AND BIOCHEMICAL ZOOLOGY',
 'BRAZILIAN JOURNAL OF MEDICAL AND BIOLOGICAL RESEARCH',
 'JOURNAL OF PARALLEL AND DISTRIBUTED COMPUTING',
 'ATOMIC DATA AND NUCLEAR DATA TABLES',
 'JOURNAL OF ALGEBRA',
 'PERIODICA POLYTECHNICA-CIVIL ENGINEERING',
 'BIOMEDICAL MATERIALS',
 'EUROPEAN JOURNAL OF PHARMACEUTICAL SCIENCES',
 'NUCLEAR INSTRUMENTS & METHODS IN PHYSICS RESEARCH SECTION A-ACCELERATORS SPECTROMETERS DETECTORS AND ASSOCIATED EQUIPMENT',
 'ACTA GEOGRAPHICA SLOVENICA-GEOGRAFSKI ZBORNIK',
 'APPLIED SURFACE SCIENCE',
 'JOURNAL OF GRAPH THEORY',
 'NEW BIOTECHNOLOGY',
 'INTERNATIONAL JOURNAL OF INTELLIGENT SYSTEMS',
 'GENES CHROMOSOMES & CANCER',
 'IEEE TRANSACTIONS ON SIGNAL PROCESSING',
 'IEEE SIGNAL PROCESSING LETTERS',
 'PROCEEDINGS OF THE AMERICAN MATHEMATICAL SOCIETY',
 'GAIT & POSTURE',
 'SIGNS',
 'EDUCATIONAL POLICY',
 'JOURNAL OF LUMINESCENCE',
 'JOURNAL OF COMPUTATIONAL PHYSICS',
 'JOURNAL OF CRYSTAL GROWTH',
 'CARBON',
 'JOURNAL OF LANGUAGE AND SOCIAL PSYCHOLOGY',
 'ANALYTICA CHIMICA ACTA',
 'URBAN EDUCATION',
 'YOUTH & SOCIETY',
 'JOURNAL OF COMPUTATIONAL CHEMISTRY',
 'JOURNAL OF MEDICAL VIROLOGY',
 'JOURNAL OF TRIBOLOGY-TRANSACTIONS OF THE ASME',
 'JOURNAL OF FLUIDS ENGINEERING-TRANSACTIONS OF THE ASME',
 'JOURNAL OF DYNAMIC SYSTEMS MEASUREMENT AND CONTROL-TRANSACTIONS OF THE ASME',
 'WORLD DEVELOPMENT',
 'INTERNATIONAL JOURNAL OF HEAT AND MASS TRANSFER',
 'SOLAR ENERGY MATERIALS AND SOLAR CELLS',
 'OPTICS COMMUNICATIONS',
 'TOXICOLOGY LETTERS',
 'ULTRASONICS',
 'POLYMER-PLASTICS TECHNOLOGY AND ENGINEERING',
 'INTERNATIONAL JOURNAL OF GENERAL SYSTEMS',
 'SUPRAMOLECULAR CHEMISTRY',
 'ANIMAL BIODIVERSITY AND CONSERVATION',
 'NATURAL PRODUCT RESEARCH',
 'ULTRAMICROSCOPY',
 'MONTHLY NOTICES OF THE ROYAL ASTRONOMICAL SOCIETY',
 'DISABILITY AND REHABILITATION',
 'JOURNAL OF ENVIRONMENTAL PLANNING AND MANAGEMENT',
 'JOURNAL OF THEORETICAL BIOLOGY',
 'DISCRETE AND CONTINUOUS DYNAMICAL SYSTEMS-SERIES S',
 'MATHEMATICAL AND COMPUTER MODELLING OF DYNAMICAL SYSTEMS',
 'STRUCTURE AND INFRASTRUCTURE ENGINEERING',
 'BIOACOUSTICS-THE INTERNATIONAL JOURNAL OF ANIMAL SOUND AND ITS RECORDING',
 'MOLECULAR SIMULATION',
 'HYDROBIOLOGIA',
 'TRAFFIC INJURY PREVENTION',
 'JOURNAL OF THE SCIENCE OF FOOD AND AGRICULTURE',
 'JOURNAL OF SYSTEMATIC PALAEONTOLOGY',
 'LABOR HISTORY',
 'JOURNAL OF BIOMECHANICAL ENGINEERING-TRANSACTIONS OF THE ASME',
 'GLIA',
 'CHILD NEUROPSYCHOLOGY',
 'JOURNAL OF STATISTICAL COMPUTATION AND SIMULATION',
 'LATERALITY',
 'JOURNAL OF THE TEXTILE INSTITUTE',
 'PSYCHOLOGY HEALTH & MEDICINE',
 'INDUSTRY AND INNOVATION',
 'JOURNAL OF TURBOMACHINERY-TRANSACTIONS OF THE ASME',
 'CROP PROTECTION',
 'LWT-FOOD SCIENCE AND TECHNOLOGY',
 'MATERIALS CHEMISTRY AND PHYSICS',
 'INTERNATIONAL JOURNAL OF FATIGUE',
 'ACTA MATERIALIA',
 'JOURNAL OF PROTEOMICS',
 'JOURNAL OF THE MECHANICS AND PHYSICS OF SOLIDS',
 'STATISTICS & PROBABILITY LETTERS',
 'INTERNATIONAL JOURNAL OF PLASTICITY',
 'ACTA TROPICA',
 'RADIATION PHYSICS AND CHEMISTRY',
 'JOURNAL OF ENVIRONMENTAL MANAGEMENT',
 'BIOMATERIALS',
 'MEAT SCIENCE',
 'JOURNAL OF PHYSICS AND CHEMISTRY OF SOLIDS',
 'MICROVASCULAR RESEARCH',
 'JOURNAL OF ENGINEERING FOR GAS TURBINES AND POWER-TRANSACTIONS OF THE ASME',
 'ENVIRONMENTAL POLITICS',
 'JOURNAL OF MATERNAL-FETAL & NEONATAL MEDICINE',
 'CRITICAL PUBLIC HEALTH',
 'ARMED FORCES & SOCIETY',
 'INTERNATIONAL JOURNAL OF CARDIOLOGY',
 'PHILOSOPHICAL TRANSACTIONS OF THE ROYAL SOCIETY B-BIOLOGICAL SCIENCES',
 'JOURNAL OF PETROLEUM SCIENCE AND ENGINEERING',
 'YOUTH VIOLENCE AND JUVENILE JUSTICE',
 'COLD REGIONS SCIENCE AND TECHNOLOGY',
 'SMART MATERIALS AND STRUCTURES',
 'JOURNAL OF AEROSOL SCIENCE',
 'JOURNAL OF FLUID MECHANICS',
 'FUZZY SETS AND SYSTEMS',
 'IRANIAN STUDIES',
 'CURRENT APPLIED PHYSICS',
 'INVERSE PROBLEMS IN SCIENCE AND ENGINEERING',
 'CRUSTACEANA',
 'RANDOM STRUCTURES & ALGORITHMS',
 'JOURNAL OF INNOVATIVE OPTICAL HEALTH SCIENCES',
 'SUSTAINABLE CITIES AND SOCIETY',
 'BUSINESS HISTORY',
 'ATMOSPHERIC RESEARCH',
 'JOURNAL OF BANKING & FINANCE',
 'JOURNAL OF PHARMACEUTICAL AND BIOMEDICAL ANALYSIS',
 'PHYSICA B-CONDENSED MATTER',
 'POLISH JOURNAL OF FOOD AND NUTRITION SCIENCES',
 'MATERIALS SCIENCE IN SEMICONDUCTOR PROCESSING',
 'JOURNAL OF APPLIED STATISTICS',
 'HOUSING STUDIES',
 'NONLINEARITY',
 'ANTIOXIDANTS & REDOX SIGNALING',
 'DRUG DEVELOPMENT AND INDUSTRIAL PHARMACY',
 'AMERICAN LITERARY REALISM',
 'HEALTH COMMUNICATION',
 'VEHICLE SYSTEM DYNAMICS',
 'ARCHIVES OF GERONTOLOGY AND GERIATRICS',
 'JOURNAL OF APPLIED ANIMAL WELFARE SCIENCE',
 'JOURNAL OF SEA RESEARCH',
 'ENVIRONMENTAL SCIENCE & POLICY',
 'ASIA PACIFIC BUSINESS REVIEW',
 'ASSESSMENT',
 'JOURNAL OF POLYMER SCIENCE PART B-POLYMER PHYSICS',
 'BIOLOGICAL PSYCHIATRY',
 'JOURNAL OF CELLULAR BIOCHEMISTRY',
 'REHABILITATION COUNSELING BULLETIN',
 'JOURNAL OF PHYSICS G-NUCLEAR AND PARTICLE PHYSICS',
 'COMPARATIVE POLITICAL STUDIES',
 'ENVIRONMENTAL MODELLING & SOFTWARE',
 'FLUID DYNAMICS RESEARCH',
 'MIDWIFERY',
 'BASIC RESEARCH IN CARDIOLOGY',
 'INTERNATIONAL JOURNAL OF NUMBER THEORY',
 'JOURNAL OF SOUND AND VIBRATION',
 'INORGANICA CHIMICA ACTA',
 'BIOTECHNOLOGY AND BIOENGINEERING',
 'JOURNAL OF POLYMER SCIENCE PART A-POLYMER CHEMISTRY',
 'PEDIATRIC BLOOD & CANCER',
 'EUROPEAN JOURNAL OF NUCLEAR MEDICINE AND MOLECULAR IMAGING',
 'PEDIATRIC NEPHROLOGY',
 'CONTEMPORARY ECONOMIC POLICY',
 'IEEE TRANSACTIONS ON APPLIED SUPERCONDUCTIVITY',
 'COMPUTERS & EDUCATION',
 'COMPUTERS & GEOSCIENCES',
 'RELIABILITY ENGINEERING & SYSTEM SAFETY',
 'FUEL PROCESSING TECHNOLOGY',
 'SURFACE SCIENCE',
 'FLUID PHASE EQUILIBRIA',
 'NUTRITION',
 'JOURNAL OF BEHAVIOR THERAPY AND EXPERIMENTAL PSYCHIATRY',
 'INTERNATIONAL JOURNAL OF FOOD MICROBIOLOGY',
 'ANNALS OF PURE AND APPLIED LOGIC',
 'CARPATHIAN JOURNAL OF EARTH AND ENVIRONMENTAL SCIENCES',
 'GENERAL AND COMPARATIVE ENDOCRINOLOGY',
 'JOURNAL OF FUNCTIONAL ANALYSIS',
 'ECOTOXICOLOGY AND ENVIRONMENTAL SAFETY',
 'COMPUTERS & SECURITY',
 'QUARTERLY OF APPLIED MATHEMATICS',
 'COMPUTER METHODS IN APPLIED MECHANICS AND ENGINEERING',
 'IEEE TRANSACTIONS ON INDUSTRIAL ELECTRONICS',
 'INSECT SYSTEMATICS & EVOLUTION',
 'INTERNATIONAL JOURNAL OF CHEMICAL KINETICS',
 'SYNAPSE',
 'RESEARCH ON AGING',
 'AMERICAN JOURNAL OF HOSPICE & PALLIATIVE MEDICINE',
 'ENERGY EXPLORATION & EXPLOITATION',
 'FEMINIST CRIMINOLOGY',
 'INDEPENDENT REVIEW',
 'COMPUTER-AIDED DESIGN',
 'PHILOSOPHICAL TRANSACTIONS OF THE ROYAL SOCIETY A-MATHEMATICAL PHYSICAL AND ENGINEERING SCIENCES',
 'NEUROBIOLOGY OF AGING',
 'APPLIED PSYCHOLOGICAL MEASUREMENT',
 'ASYMPTOTIC ANALYSIS',
 'SUPPORTIVE CARE IN CANCER',
 'SKELETAL RADIOLOGY',
 'CARBOHYDRATE POLYMERS',
 'JOURNAL OF ALZHEIMERS DISEASE',
 'TICKS AND TICK-BORNE DISEASES',
 'ANNALS OF PHARMACOTHERAPY',
 'ENVIRONMENT AND BEHAVIOR',
 'ULTRASONIC IMAGING',
 'ECOLOGICAL ECONOMICS',
 'JOURNAL OF ETHNOPHARMACOLOGY',
 'NEW REPUBLIC',
 'ROAD MATERIALS AND PAVEMENT DESIGN',
 'JOURNAL OF BRITISH CINEMA AND TELEVISION',
 'NEURAL NETWORKS',
 'ELECTRIC POWER SYSTEMS RESEARCH',
 'SOCIAL NETWORKS',
 'PALAEOGEOGRAPHY PALAEOCLIMATOLOGY PALAEOECOLOGY',
 'BIOCHIMICA ET BIOPHYSICA ACTA-GENERAL SUBJECTS',
 'INTERNATIONAL JOURNAL OF REFRACTORY METALS & HARD MATERIALS',
 'GEOCHIMICA ET COSMOCHIMICA ACTA',
 'COMPUTER METHODS AND PROGRAMS IN BIOMEDICINE',
 'ANALYTICAL LETTERS',
 'FINITE ELEMENTS IN ANALYSIS AND DESIGN',
 'ARCHIVES OF CIVIL AND MECHANICAL ENGINEERING',
 'JOURNAL OF COGNITIVE NEUROSCIENCE',
 'JOURNAL OF INTERDISCIPLINARY HISTORY',
 'CHINESE JOURNAL OF POLYMER SCIENCE',
 'PUBLICACIONS MATEMATIQUES',
 'JOURNAL OF AGING AND HEALTH',
 'JOURNAL OF ADOLESCENT RESEARCH',
 'CHEMISTRY LETTERS',
 'TELEVISION & NEW MEDIA',
 'MODERN CHINA',
 'JOURNAL OF BUSINESS AND TECHNICAL COMMUNICATION',
 'JOURNAL OF DRUG ISSUES',
 'JOURNAL OF EDUCATIONAL COMPUTING RESEARCH',
 'WESTERN JOURNAL OF NURSING RESEARCH',
 'BUILDING SIMULATION',
 'JOURNAL OF HOSPITALITY & TOURISM RESEARCH',
 'JOURNAL OF SPORTS ECONOMICS',
 'CRIME & DELINQUENCY',
 'HUMAN & EXPERIMENTAL TOXICOLOGY',
 'ANIMAL PRODUCTION SCIENCE',
 'CRETACEOUS RESEARCH',
 'ENERGY POLICY',
 'PHYSICS LETTERS A',
 'APPETITE',
 'BIOCHIMICA ET BIOPHYSICA ACTA-PROTEINS AND PROTEOMICS',
 'JOURNAL OF VIROLOGICAL METHODS',
 'JOURNAL OF INTERPROFESSIONAL CARE',
 'JOURNAL OF ELEMENTOLOGY',
 'ADVANCES IN ENGINEERING SOFTWARE',
 'JOURNAL OF GYNECOLOGIC ONCOLOGY',
 'INTERNATIONAL JOURNAL OF ONCOLOGY',
 'JOURNAL OF GEOCHEMICAL EXPLORATION',
 'SIMULATION MODELLING PRACTICE AND THEORY',
 'ENGINEERING FAILURE ANALYSIS',
 'JOURNAL OF RESEARCH IN MUSIC EDUCATION',
 'HUMAN RELATIONS',
 'LATIN AMERICAN PERSPECTIVES',
 'EMPIRICAL STUDIES OF THE ARTS',
 'CLINICAL PEDIATRICS',
 'AMERICAN REVIEW OF PUBLIC ADMINISTRATION',
 'AMBIO',
 'SURGERY TODAY',
 'INTERNATIONAL JOURNAL OF ELECTRONICS',
 'DEVELOPMENT POLICY REVIEW',
 'EQUINE VETERINARY EDUCATION',
 'EQUINE VETERINARY JOURNAL',
 'CERAMICS INTERNATIONAL',
 'BRAIN BEHAVIOR AND IMMUNITY',
 'MATERIALS SCIENCE AND ENGINEERING A-STRUCTURAL MATERIALS PROPERTIES MICROSTRUCTURE AND PROCESSING',
 'INTERNATIONAL JOURNAL OF APPLIED GLASS SCIENCE',
 'JOURNAL OF APPLIED MECHANICS-TRANSACTIONS OF THE ASME',
 'INTERNATIONAL JOURNAL OF QUANTUM CHEMISTRY',
 'HISTOLOGY AND HISTOPATHOLOGY',
 'JOURNAL OF COMPARATIVE NEUROLOGY',
 'MAGAZINE OF CONCRETE RESEARCH',
 'BIOLOGICAL CHEMISTRY',
 'JOURNAL OF PRODUCT INNOVATION MANAGEMENT',
 'MICROWAVE AND OPTICAL TECHNOLOGY LETTERS',
 'PHYTOCHEMICAL ANALYSIS',
 'HEART LUNG AND CIRCULATION',
 'RESPIROLOGY',
 'AQUATIC LIVING RESOURCES',
 'INTERNATIONAL JOURNAL OF INFORMATION MANAGEMENT',
 'INTERNATIONAL JOURNAL OF MEDICAL INFORMATICS',
 'REPRODUCTION FERTILITY AND DEVELOPMENT',
 'RESEARCH IN SOCIAL & ADMINISTRATIVE PHARMACY',
 'MOLECULAR PHARMACOLOGY',
 'ANKARA UNIVERSITESI VETERINER FAKULTESI DERGISI',
 'ARCHAEOLOGY',
 'FINITE FIELDS AND THEIR APPLICATIONS',
 'AD HOC NETWORKS',
 'INTERNET AND HIGHER EDUCATION',
 'APPLIED CATALYSIS A-GENERAL',
 'AGRICULTURAL WATER MANAGEMENT',
 'SAFETY SCIENCE',
 'PHYSIOLOGY & BEHAVIOR',
 'NONLINEAR ANALYSIS-HYBRID SYSTEMS',
 'NONLINEAR ANALYSIS-THEORY METHODS & APPLICATIONS',
 'ORGANIC ELECTRONICS',
 'CURRENT GENOMICS',
 'EXPRESS POLYMER LETTERS',
 'BEHAVIOR MODIFICATION',
 'ACTA NEUROLOGICA SCANDINAVICA',
 'EDUCATION AND URBAN SOCIETY',
 'GAMES AND CULTURE',
 'BIOLOGICAL CONTROL',
 'JOURNAL OF INTENSIVE CARE MEDICINE',
 'BIOORGANIC & MEDICINAL CHEMISTRY LETTERS',
 'ULTRASOUND IN MEDICINE AND BIOLOGY',
 'BIORESOURCE TECHNOLOGY',
 'UROLOGIC ONCOLOGY-SEMINARS AND ORIGINAL INVESTIGATIONS',
 'JOURNAL OF PEDIATRIC ONCOLOGY NURSING',
 'ECOLOGICAL ENGINEERING',
 'CATALYSIS TODAY',
 'COLLOIDS AND SURFACES A-PHYSICOCHEMICAL AND ENGINEERING ASPECTS',
 'PSYCHOLOGY OF MUSIC',
 'JOURNAL OF MANUFACTURING SCIENCE AND ENGINEERING-TRANSACTIONS OF THE ASME',
 'ELECTRONIC MATERIALS LETTERS',
 'SYNTHESE',
 'JOURNAL OF ENERGY RESOURCES TECHNOLOGY-TRANSACTIONS OF THE ASME',
 'EARTHQUAKE ENGINEERING & STRUCTURAL DYNAMICS',
 'FORENSIC SCIENCE INTERNATIONAL-GENETICS',
 'ETHOLOGY',
 'FATIGUE & FRACTURE OF ENGINEERING MATERIALS & STRUCTURES',
 'INTERNATIONAL JOURNAL OF APPLIED CERAMIC TECHNOLOGY',
 'FOLK MUSIC JOURNAL',
 'CLINICS IN PLASTIC SURGERY',
 'AMERICAN HISTORY',
 'MOLECULAR CARCINOGENESIS',
 'COMMUNICATIONS ON PURE AND APPLIED ANALYSIS',
 'PROSTATE',
 'MULTISENSORY RESEARCH',
 'CZECH JOURNAL OF ANIMAL SCIENCE',
 'BLOOD CELLS MOLECULES AND DISEASES',
 'EUROPEAN RADIOLOGY',
 'ACTA AGRICULTURAE SCANDINAVICA SECTION B-SOIL AND PLANT SCIENCE',
 'BUILDING RESEARCH AND INFORMATION',
 'HIV MEDICINE',
 'MEMORIAS DO INSTITUTO OSWALDO CRUZ',
 'INTERNATIONAL JOURNAL OF GYNECOLOGY & OBSTETRICS',
 'GEOPHYSICAL JOURNAL INTERNATIONAL',
 'INTERNATIONAL JOURNAL OF SHIPPING AND TRANSPORT LOGISTICS',
 'ACTA ANAESTHESIOLOGICA SCANDINAVICA',
 'METALLURGICAL RESEARCH & TECHNOLOGY',
 'ECOLOGY OF FRESHWATER FISH',
 'JOURNAL OF MEDICAL BIOCHEMISTRY',
 'ANAESTHESIA',
 'SECOND LANGUAGE RESEARCH',
 'LUPUS',
 'MOLECULAR PHYLOGENETICS AND EVOLUTION',
 'MODERN THEOLOGY',
 'JOURNAL OF FIRE SCIENCES',
 'NETWORKS',
 'PACKAGING TECHNOLOGY AND SCIENCE',
 'JNCI-JOURNAL OF THE NATIONAL CANCER INSTITUTE',
 'CHILDREN & SOCIETY',
 'REVISTA DE PSICODIDACTICA',
 'CONCURRENCY AND COMPUTATION-PRACTICE & EXPERIENCE',
 'ADVANCES IN ATMOSPHERIC SCIENCES',
 'X-RAY SPECTROMETRY',
 'ECONOMICA',
 'ECONOMICS OF TRANSITION',
 'DIABETOLOGIA',
 'FLAVOUR AND FRAGRANCE JOURNAL',
 'HUMAN BRAIN MAPPING',
 'JOURNAL OF SHOULDER AND ELBOW SURGERY',
 'SOLID-STATE ELECTRONICS',
 'IBIS',
 'GOVERNMENT AND OPPOSITION',
 'INFANCY',
 'INTERNATIONAL JOURNAL FOR NUMERICAL AND ANALYTICAL METHODS IN GEOMECHANICS',
 'EUROPEAN JOURNAL OF CANCER PREVENTION',
 'EUROPEAN JOURNAL OF GASTROENTEROLOGY & HEPATOLOGY',
 'INTERNATIONAL CLINICAL PSYCHOPHARMACOLOGY',
 'UKRAINIAN MATHEMATICAL JOURNAL',
 'JOURNAL OF MECHANICAL DESIGN',
 'NEUROREPORT',
 'ADMINISTRATION & SOCIETY',
 'JOURNAL OF WATERWAY PORT COASTAL AND OCEAN ENGINEERING',
 'JOURNAL OF WATER RESOURCES PLANNING AND MANAGEMENT',
 'ROBOTICA',
 'REPRODUCTIVE SCIENCES',
 'JOURNAL OF MANAGEMENT',
 'PHILOSOPHY OF THE SOCIAL SCIENCES',
 'SURGICAL ONCOLOGY CLINICS OF NORTH AMERICA',
 'JOURNAL OF MATERIALS IN CIVIL ENGINEERING',
 'JOURNAL OF MANAGEMENT IN ENGINEERING',

In [34]:
import nltk 

key_words = ['sustainable', 'sustainibility', 'renewable']

key_journals = []

for line in j_list:
    tmp = line.split()
    for word in key_words:
        for w in tmp:
            if w.lower()==word.lower():
                tmp1 = w
                tmp2 = tmp
                key_journals.append([tmp1, tmp2])
key_journals

[['RENEWABLE', ['RENEWABLE', 'ENERGY']],
 ['SUSTAINABLE', ['SUSTAINABLE', 'CITIES', 'AND', 'SOCIETY']],
 ['SUSTAINABLE', ['ENERGY', 'FOR', 'SUSTAINABLE', 'DEVELOPMENT']],
 ['SUSTAINABLE', ['IEEE', 'TRANSACTIONS', 'ON', 'SUSTAINABLE', 'ENERGY']],
 ['SUSTAINABLE', ['AGROECOLOGY', 'AND', 'SUSTAINABLE', 'FOOD', 'SYSTEMS']],
 ['RENEWABLE', ['IET', 'RENEWABLE', 'POWER', 'GENERATION']],
 ['SUSTAINABLE', ['ACS', 'SUSTAINABLE', 'CHEMISTRY', '&', 'ENGINEERING']],
 ['SUSTAINABLE', ['ENVIRONMENTAL', 'PROGRESS', '&', 'SUSTAINABLE', 'ENERGY']],
 ['SUSTAINABLE', ['JOURNAL', 'OF', 'SUSTAINABLE', 'TOURISM']],
 ['RENEWABLE', ['RENEWABLE', 'AGRICULTURE', 'AND', 'FOOD', 'SYSTEMS']],
 ['SUSTAINABLE', ['SUSTAINABLE', 'ENERGY', '&', 'FUELS']],
 ['SUSTAINABLE',
  ['INTERNATIONAL',
   'JOURNAL',
   'OF',
   'SUSTAINABLE',
   'DEVELOPMENT',
   'AND',
   'WORLD',
   'ECOLOGY']],
 ['SUSTAINABLE',
  ['INTERNATIONAL', 'JOURNAL', 'OF', 'SUSTAINABLE', 'TRANSPORTATION']],
 ['SUSTAINABLE', ['SUSTAINABLE', 'DEVELOPMENT']],
 ['SUSTAINABLE', ['AGRONOMY', 'FOR', 'SUSTAINABLE', 'DEVELOPMENT']],
 ['SUSTAINABLE',
  ['JOURNAL', 'OF', 'RENEWABLE', 'AND', 'SUSTAINABLE', 'ENERGY']],
 ['RENEWABLE', ['JOURNAL', 'OF', 'RENEWABLE', 'AND', 'SUSTAINABLE', 'ENERGY']],
 ['SUSTAINABLE', ['SUSTAINABLE', 'COMPUTING-INFORMATICS', '&', 'SYSTEMS']],
 ['SUSTAINABLE', ['JOURNAL', 'OF', 'SUSTAINABLE', 'FORESTRY']],
 ['RENEWABLE', ['JOURNAL', 'OF', 'RENEWABLE', 'MATERIALS']],
 ['SUSTAINABLE', ['RENEWABLE', '&', 'SUSTAINABLE', 'ENERGY', 'REVIEWS']],
 ['RENEWABLE', ['RENEWABLE', '&', 'SUSTAINABLE', 'ENERGY', 'REVIEWS']],
 ['SUSTAINABLE',
  ['SUSTAINABLE', 'ENERGY', 'TECHNOLOGIES', 'AND', 'ASSESSMENTS']],
 ['SUSTAINABLE', ['SUSTAINABLE', 'ENERGY', 'GRIDS', '&', 'NETWORKS']],
 ['SUSTAINABLE', ['SUSTAINABLE', 'CHEMISTRY', 'AND', 'PHARMACY']]]

In [35]:
print(f'there are {len(key_journals)} journals using key words: {[i for i in key_words]}')

there are 25 journals using key words: ['sustainable', 'sustainibility', 'renewable']

In [52]:
df_only_renewable_energy = df.loc[df['Journal_Name'] == 'RENEWABLE ENERGY']
df_only_renewable_energy

,Publication_Code,Journal_Name,Title,Abstract
4489,413615500001,RENEWABLE ENERGY,Effect of leaching pretreatment on the gasific...,Utilization of biomass residues for energetic ...
4490,413615500002,RENEWABLE ENERGY,Numerical definitions of wind power output flu...,Because of unpredictable fluctuations in wind ...
4491,413615500003,RENEWABLE ENERGY,Impact of altitude and power rating on power-t...,This paper presents a static comprehensive opt...
4492,413615500004,RENEWABLE ENERGY,Structuring financial incentives for residenti...,This paper introduces a simple methodology to ...
4493,413615500005,RENEWABLE ENERGY,Investigation into parameter influence of upst...,This paper presents the parameter influence of...
...,...,...,...,...
959549,440771200016,RENEWABLE ENERGY,In-vessel co-composting of biosolid: Focusing ...,In this paper study the feasibility of Calcium...
959550,440771200017,RENEWABLE ENERGY,Feasible use of microbial fuel cells for pollu...,The microbial fuel cells (MFC) can directly tr...
959551,440771200018,RENEWABLE ENERGY,Analyzing animal waste-to-energy supply chains...,"To reduce human impact upon the environment, a..."
959552,440771200019,RENEWABLE ENERGY,Sustainable approaches for algae utilisation i...,Rapidly increasing global energy consumption h...
959553,440771200020,RENEWABLE ENERGY,Model for evaluation of locally available biom...,The paper presents the methodology and the cas...

In [60]:
# don't delete!! 
df_only_renewable_energy.iloc[0, 3]

'Utilization of biomass residues for energetic purposes increases the share of renewables in the total energy balance. Gasification is one of the thermochemical processes that converts solid biomass to valuable gaseous products. Prior to the gasification process, biomass material could be treated to improve the quality or composition of the product gas. Our focus is on fluidized bed gasification of untreated vine and pretreated vine residue and pretreated wine residue. Natural and artificial leaching were used as pretreatment methods. Our results showed that CO and H-2 content in the product gas are higher in leached (16.9 and 10.0% respectively) vine residue than in untreated material (14.5 and 7.7% respectively). The naturally leached wine residue was found to have the highest CO content (18.1%) and relatively high H2 content (9.7%) in the product gas, but lower CH4 (1.0%) and CO2 content (5.6%). The results of tar measurements indicated that the leaching pre-treatment lowers the tar content in the evolved product gas, e.g. by 36% in the case of vine residues. As a result, the controlled leaching pretreatment is recommended as an effective way of upgrading the composition of agricultural biomass. (C) 2017 Elsevier Ltd. All rights reserved.'

In [64]:
policy_key_words = "ensure access to affordable, reliable, sustainable and modern energy for all"
policy_key_words = policy_key_words.split()
policy_key_words

['ensure',
 'access',
 'to',
 'affordable,',
 'reliable,',
 'sustainable',
 'and',
 'modern',
 'energy',
 'for',
 'all']

In [65]:
policy_key_words = ['ensure',
 'access',
 'affordable,',
 'reliable,',
 'sustainable',
 'modern',
 'energy']

In [70]:
renewable_energy_abstracts = []
for i in range(len(df_only_renewable_energy)):
    renewable_energy_abstracts.append(df_only_renewable_energy.iloc[i,3])

In [71]:
renewable_energy_abstracts

['Utilization of biomass residues for energetic purposes increases the share of renewables in the total energy balance. Gasification is one of the thermochemical processes that converts solid biomass to valuable gaseous products. Prior to the gasification process, biomass material could be treated to improve the quality or composition of the product gas. Our focus is on fluidized bed gasification of untreated vine and pretreated vine residue and pretreated wine residue. Natural and artificial leaching were used as pretreatment methods. Our results showed that CO and H-2 content in the product gas are higher in leached (16.9 and 10.0% respectively) vine residue than in untreated material (14.5 and 7.7% respectively). The naturally leached wine residue was found to have the highest CO content (18.1%) and relatively high H2 content (9.7%) in the product gas, but lower CH4 (1.0%) and CO2 content (5.6%). The results of tar measurements indicated that the leaching pre-treatment lowers the tar content in the evolved product gas, e.g. by 36% in the case of vine residues. As a result, the controlled leaching pretreatment is recommended as an effective way of upgrading the composition of agricultural biomass. (C) 2017 Elsevier Ltd. All rights reserved.',
 'Because of unpredictable fluctuations in wind power output caused by sudden changes in weather conditions, operations that balance supply and demand in power systems will gradually become more difficult with the massive deployment of wind power generation. Therefore, it is necessary to quantitatively evaluate wind power output fluctuations in a way that corresponds to frequency controls in power system operations. In this study, we analyzed data for the fluctuations of actual wind power output at 20 wind farms, as designated by three basic definitions: the changes in time-averaged values, the maximum power-fluctuation range within a time window, and the deviations from a centered moving average value. The results indicated relevant differences between the definitions and demonstrated the importance of percentile analysis. We proposed a novel quantitative definition of the output fluctuations associated with the frequency controls of power systems: primary turbine-governor control, secondary load-frequency control, and tertiary economic load-dispatch control. Using these definitions to quantify fluctuations demonstrates how each smoothing technique can contribute to reducing the reserve capacity necessary for frequency control in the power system operations. Our proposed definitions for dividing the frequency ranges of the fluctuations were confirmed as a convenient and practical method for quantitatively evaluating the fluctuations and determining the reserve capacity required for stable power system operations. (C) 2017 Elsevier Ltd. All rights reserved.',
 "This paper presents a static comprehensive optimization study and analysis of the high altitude wind power (HAWP) generating system based on the medium voltage AC (MV-AC) transmission. The analytical expressions for weight and cost of the transmission line, the mechanical structures (turbine + frame), the generator, and the blimp/aerostat are derived as functions of output power rating and altitude. The optimal voltages for the MV-AC transmission of the HAWP for various power ratings and altitudes are evaluated using the derived equations. The optimal transmission voltage, thus obtained is used to estimate the weight of the tether wire (transmission line) and the generator. The weight of the mechanical frame, the air-borne wind turbine (AWT), and the light gas (Hydrogen/Helium) filled blimp are also estimated for different power ratings and altitudes. The material costs of each major component of the HAWP generating system are obtained from the manufacturers' datasheets and used to compute the overall material cost. From the estimated weight and cost, the overall power-to-weight (P/W) and power to-cost (P/C) ratios of the HAWP generating system are evaluated. Finally, the optimal operating altitude for a specific power rating that exhibits the best P/W and reasonably good P/C ratios can be selected for the development and installation of the HAWP generating system. (C) 2017 Elsevier Ltd. All rights reserved.",
 'This paper introduces a simple methodology to aid in the decision of how to distribute financial incentive funding for residential solar electric systems in order to maximize demand. Incentive funding can be used more effectively if adjusted according to the decrease in price and the increase in demand of solar electric systems. The decision of how to reduce these incentives due to changing annual funds, while increasing or even maintaining the growth of solar electric system demand; is of great interest to policymakers and public benefit funded program administrators. In order to aid in this process, a three step methodology is described in this paper. The first step uses the concept of learning-by-doing to determine the relationship between historic pricing and demand. The second step employs discrete choice modeling with spatial analysis to determine the relationship between market, financial, and social factors with historic demand. The final step uses nonlinear programming to forecast incentive structuring for maximizing demand. Finally in order to validate the model the study uses solar market data from Portland, Oregon. The results show a decrease in incentives over the period of study from 2014 until 2020, except for 2017 and 2018 when federal and state tax credits expire respectively. (C) 2017 Elsevier Ltd. All rights reserved.',
 'This paper presents the parameter influence of upstream deflector on the performance of vertical axis wind turbines (VAWTs). For this purpose, two counter-rotating straight-bladed VAWTs and the upstream deflector have been simulated via three-dimensional (3D) computational fluid dynamics (CFD), which is validated against experimental data. Parameter Influence of upstream deflector on VAWTs output power is investigated in this study. From the CFD results, it is observed that when the turbine is positioned outside the near-wake region, the aerodynamic power can increase significantly.) This research indicates that performance of VAWTs can be greatly improved by properly choosing parameters of the deflector. (C) 2017 Elsevier Ltd. All rights reserved.',
 "A hydropower conversion system based on vortex-induced vibrations is investigated experimentally. It consists in a cylinder immerged in a low-velocity flow in a channel (under 1 m/s), which is linked to a variable stiffness spring, so that the natural frequency of the system might be controlled. Current studies report investigations on marine applications. Although rivers or channels constitute a strong energy potential, they are not exploited enough. In this paper, we will investigate the feasibility of such a system implantation in a confined flow in a channel, with important edge effects. We propose a study of the effects of a confined flow on the efficiency of the system. We will highlight feasible improvements, particularly through automatic control strategies (generator behaviour, system's natural frequency). Moreover, we show the strong influence of confinement on the flow topology through velocity field measurements using pulse-pair method. (C) 2017 Elsevier Ltd. All rights reserved.",
 'The Brushless Doubly-fed Induction Generator (BDFIG) has high potential for wind energy systems, especially for offshore applications where minimum maintenance is vital. The machine low voltage ride through (LVRT) capability in the light of current grid code requirements was investigated using a precise dynamic model. This is particularly important for future multi- MW BDFIGs. This paper shows the necessity for improvements of the BDFIG LVRT capability with presenting a comprehensive analytical study during asymmetrical voltage dips. Analytical studies are conducted to extract a more precise equivalent circuit model of the BDFIG used for analyzing machine dynamic behavior under various fault conditions. In addition, a comparison between different voltage dips is performed to identify critical operating points for LVRT assessment. The results of the study are verified by coupled-circuit model, simulated in MATLAB/Simulink for a BDFIG prototype. (C) 2017 Elsevier Ltd. All rights reserved.',
 'The biogas fermentation co-digestion Salvinia molesta (SM) and rice straw (RS) was investigated within a wide range of SM:RS of 100:0-0:100 (mass ratio). This study used batch anaerobic digesters in laboratory-scale operated at mesophilic temperature in 30 days. The optimum SM:RS ratio was 60:40 -0:100 (C/N of 29.50-39.17) producing total biogas yield of 103.83-113.92 mL/g VS. The highest biogas yield (113.92 +/- 6.90 mL/g VS) was obtained from SM:RS of 40:60 (C/N of 34.80). The biogas produced from SM:RS of 40:60 contained 60.58% CH4, 38.69% CO2, 0.73% H-2. Fitting error between measured and predicted total biogas yield for 30 days fermentation by using modified Gompertz, Cone, First Order model was 0.96-6.45%, 0.14-3.52%, and 1.97-15.25% respeCtively. Furthermore, Cone model was used to design the anaerobic batch digester volume and develop the kinetic model of VS degradability rate. The fit correlation of measured and predicted VS removal was R-2 = 0.992. (C) 2017 Elsevier Ltd. All rights reserved.',
 'Nowadays, the society faces the challenge of continuous supply of electricity. Energy from two different sources of origin such as renewable and non-renewable is used to meet the needs of modern humankind. The paper presents the findings concerning the thermo-ecological cost assessment of renewable energy sources defining their total impact on the environment. Biogas, wind and photovoltaic power plants were evaluated to present the results of cumulative environmental impact based on the thermo-ecological cost methodology. Polish law regulations and the prediction of the future energy mix structure are described to emphasize the importance of selected technologies. The measurements data of real renewable energy units in Poland and the characteristics of components were used to calculate thermo-ecological cost of electricity originating from renewable sources. Moreover, different phases of the production chain are considered to present results in total life cycle of the respective technologies. In the calculations, continuous availability of conventional power plants for stabilizing the current electricity needs is taken into account. Finally, the results of this study prove that biogas power plants cause lower environmental impact than wind and photovoltaic technologies. (C) 2017 Elsevier Ltd. All rights reserved.',
 'The Kansas Project aims to establish a synergetic link between people and weather, as well as to explore different ways to harness the weather for its sustainable resources. The site is located in the South Central Kansas, United States. This case study presents wind and tornado climatology analyses coupled with a wind resource assessment study for this modern development. The wind analyses are conducted using wind data from weather station located in Medicine Lodge and for the period 1984-2015. The mean annual wind speed at the site is 4.45 m s(-1) at 10 m height. The north-south bi-directionality of the wind rose is very pronounced. The mean annual wind speeds have a positive, but statistically not significant trend. A 50-year return period 5-s gust of 34 m s(-1) is estimated at 10 m height. The deadliest and most damaging tornadoes around the site are F3 twisters, while the most common tornadoes are F2 and weaker. The WAsP package is used to calculate the regional wind atlas for five heights and five reference roughness lengths. Wind resource grids depict good wind energy potential at 50, 80, 100 and 150 m levels. In addition, roughness and topographic uncertainties related to WASP performance are addressed in details. (C) 2017 Elsevier Ltd. All rights reserved.',
 'This paper presents a numerical workflow designed and developed for autonomous synthesis of vertical axis wind turbine (VAWT) blades for maximum annual energy production at a specified location given by specified wind speed distribution and prescribed tip speed ratio. The workflow can synthesize shapes of both classical VAWT designs: Darrieus and Savonius rotors. This is achieved using a novel shape parameterization scheme based on B-splines which represents a compromise between shape generality and the multitude of shape variables. The developed computational framework enables the optimizer to synthesize and evaluate a variety of geometrically and even topologically different shapes such as the Darrieus and Savonius types. Moreover, the workflow can invent (i.e. numerically generate without a resembling initial shape) new generic shapes for custom operating conditions. Both single wind-speed and systems related to real-site operating conditions specified by a given distribution of wind speeds are considered. The developed workflow consists of efficient geometry parameterization, a genetic algorithm based optimizer and a computational fluid dynamics based simulator. The rather promising results of custom-shaped vertical axis wind turbines for maximum annual energy production at a given specific site are presented using a set of case studies. (C) 2017 Elsevier Ltd. All rights reserved.',
 'The output of Photovoltaic (PV) panel varies with panel temperature and in order to obtain uniform output from PV panels, water cooling system is recommended by several researchers worldwide. In this study, a laboratory scale experimental setup is developed (irradiance over the PV panel is varied from 87.38 W/m(2) to 359.17 W/m(2) and back to initial value in a triangular cyclic shape analogous to daytime radiation variation) for intermittent and continuous water cooling, which is tested for different flow rates. A mathematical analysis of temperature over PV panel with and without water cooling system is also done. For intermittent cooling case, three different flow rates of 3 lit/min, 5.3 lit/min, and 6.2 lit/min are used, which give an increase in total energy produced against no cooling operation of about 18% for all the three cases. The test results for continuous cooling (wherein a fixed flow rate of 0.6 lit/min was maintained), the total energy produced increases by approximately 29% against no-cooling operation. The proposed method of cooling the PV panels can be integrated with the water supply system of domestic dwellings. Further, a parametric study is carried out in order to choose the appropriate capacity of pump required for the operation. The proposed approach of integrating cooling of PV panels and water supply minimizes water loss (except evaporation loss) and reuses the cooling water back into the main water supply system of the dwelling. It is observed that the continuous cooling system with a water pump of appropriate capacity improves the performance of PV panels while keeping the consumption of water to minimum. (C) 2017 Elsevier Ltd. All rights reserved.',
 'Pretreatment is necessary to improve methane production from lignocellulosic biomass. Urea was adopted to pretreat wheat straw with the advantages of structure deconstruction, its nitrogen source, and prevention of pH drop in subsequent anaerobic digestion (AD). Scanning electron microscopy (SEM), X-ray diffraction analysis (XRD) and Fourier transform infrared spectroscopy (FTIR) spectra measurements indicated that urea pretreatment is able to degrade the lignocellulosic structure, which was beneficial for the improvement of methane production. Urea pretreatment led to the satisfactory performance of AD with wheat straw as substrate. The maximum methane production of 305.5 L/kg volatile solids (VS) was obtained using 1% (w/w) urea loading, which was 45.2% higher than the untreatment. After 1%- and 3%-urea treatment, time used for achieving stable status (>= 50%) was 2 days earlier compared to untreatment. Reductions of total solids (49.4%), VS (54.5%), cellulose (50.4%) and hemi-celluloses (47.3%) on the optimal condition were the highest, which were 36.8%, 46.5%, 33.3% and 47.4% higher compared to untreatment. Higher levels of urea pretreatment (3% and 5%) were less efficient and resulted in the formation of pseudo-lignin according to FTIR. These results indicate that wheat straw can be used to produce methane significantly with urea pretreatment. (C) 2017 Elsevier Ltd. All rights reserved.',
 "A collective pitch control system is designed using a rack and pinion gear set and hydraulic drive to provide an available blade pitch angle from 0 degrees to 180 degrees. This response accounts for the tidal current bi-directionality caused by flood and ebb under the moon's gravitational force. A front-installed hydraulic cylinder drives the rack-and-pinion system to synchronously turn the blades. Mechanisms are designed to overcome the difficulties of an outer hydraulic oil being deposited into the rotary hub and the pitch angle detection in a rotary hub. This simple and compact structure in a narrow hub reduces current blocking. Experimental results demonstrate that the pitch system has excellent dynamic characteristics. A tidal current velocity preview (CVP) method is proposed to overcome the difficulty of current velocity detection at the rotary impeller. Sealing is important for these underwater conditions. Hence, a reduced variation pitch control strategy is proposed based on CVP to reduce pitch action, which decreases mechanical wear of the sealing structure while extending the tidal current turbine's working life. Comparative results are obtained by using both an approximate sinusoidal current velocity data set simulating periods of real flow and a sea trial measured data set containing highly-turbulent and velocity-sheared flow in a semi-physical test. This test validated the significant reduction of pitch action and relatively high efficiency for energy generation. (C) 2017 Published by Elsevier Ltd.",
 'The paper describes the theoretical modelling and experimental validation of a novel design of ocean wave energy converter which is comprised of a floating, moored, spherical hull containing a mechanical pendulum arrangement from which power is taken when excited by incident waves. Experimental results are shown to compare favourably with those predicted by the theory. An explicit expression is derived for the capture width of the proposed device in terms of physical and hydrodynamic parameters. This exposes the multiple resonant characteristics of the device which enable it to operate effectively over a broad range of wave periods. The subsequent efficient computations allows a numerical optimisation of the design to be performed over a large space of device parameters and model sea spectrum. The work is focussed towards producing reliable estimates for the power capacity of different sized devices deployed at the EMEC site in Scotland. Predictions compare favourably with existing wave energy converter concepts. (C) 2017 Elsevier Ltd. All rights reserved.',

# Next steps:
- need to grab all the abstracts out of the `renewable_energy_abstracts` that meet the condition:
 - (peudo code) if any word (using split, etc.) in abstracts contain a policy_key_word then human view those, otherwise, chuck away
- have to remember to grab the unique identifier to so we can reference those articles later

In [74]:
tokenise renewable_energy_abstracts
len(renewable_energy_abstracts[0])

1260